language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "804259890"
  - git config user.email "804259890@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://blog@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-resource
env:
 global:
   - GH_REF: github.com/804259890/blog.git